**Name**: Devyani Sanjay Gurgude **Div**: SEDA **Roll**: 09 **PRN no**:1252090009

**Assignment No: 01**

Perform the following operations using Python on suitable data sets:

1.Read data from different formats (like csv, xls)

2.Find Shape of Data

3.Find Missing Values

4.Find data type of each column

5.Finding out Zero's

6.Indexing and selecting data, sort data,

7.Describe attributes of data, checking data types of each column,

8.counting unique values of data, format of each column, converting
variable data type (e.g. from long to short, vice versa)

In [ ]:
import pandas as pd
import numpy as np
house_df = pd.read_csv("house_price.csv")
house_df

,House_ID,Location,Bedrooms,Bathrooms,Area_sqft,Year_Built,Parking,Price_Lakhs
0,1,Pune,2.0,1,850.0,2015,1,45
1,2,Mumbai,NaN,2,1200.0,2012,1,120
2,3,Delhi,4.0,3,1800.0,2018,2,95
3,4,Bangalore,3.0,2,NaN,2016,1,85
4,5,Chennai,2.0,1,900.0,2010,0,60
5,6,Pune,3.0,2,1400.0,2019,1,78
6,7,Mumbai,4.0,3,2000.0,2014,2,150
7,8,Delhi,2.0,1,800.0,2008,0,55

Find Shape of Data

In [ ]:
house_df.shape

(8, 8)

Find Missing Values

In [ ]:
house_df.isnull().sum()

House_ID       0
Location       0
Bedrooms       1
Bathrooms      0
Area_sqft      1
Year_Built     0
Parking        0
Price_Lakhs    0
dtype: int64

If missing values exist

In [ ]:
house_df.isnull().values.any()

np.True_

Find datatype of each column

In [ ]:
house_df.dtypes

House_ID          int64
Location       category
Bedrooms        float64
Bathrooms       float64
Area_sqft       float64
Year_Built        int64
Parking           int64
Price_Lakhs       int64
dtype: object

Finding Out Zero's

In [ ]:
(house_df==0).sum()

House_ID       0
Location       0
Bedrooms       0
Bathrooms      0
Area_sqft      0
Year_Built     0
Parking        2
Price_Lakhs    0
dtype: int64

In [ ]:
(house_df.select_dtypes(include=np.number) == 0).sum()

House_ID       0
Bedrooms       0
Bathrooms      0
Area_sqft      0
Year_Built     0
Parking        2
Price_Lakhs    0
dtype: int64

Indexing ,Selecting , Sorting

In [ ]:
house_df.head()

,House_ID,Location,Bedrooms,Bathrooms,Area_sqft,Year_Built,Parking,Price_Lakhs
0,1,Pune,2.0,1,850.0,2015,1,45
1,2,Mumbai,NaN,2,1200.0,2012,1,120
2,3,Delhi,4.0,3,1800.0,2018,2,95
3,4,Bangalore,3.0,2,NaN,2016,1,85
4,5,Chennai,2.0,1,900.0,2010,0,60

In [ ]:
house_df.tail()

,House_ID,Location,Bedrooms,Bathrooms,Area_sqft,Year_Built,Parking,Price_Lakhs
3,4,Bangalore,3.0,2,NaN,2016,1,85
4,5,Chennai,2.0,1,900.0,2010,0,60
5,6,Pune,3.0,2,1400.0,2019,1,78
6,7,Mumbai,4.0,3,2000.0,2014,2,150
7,8,Delhi,2.0,1,800.0,2008,0,55

Select Rows using Index

In [ ]:
house_df.iloc[0]

House_ID           1
Location        Pune
Bedrooms         2.0
Bathrooms          1
Area_sqft      850.0
Year_Built      2015
Parking            1
Price_Lakhs       45
Name: 0, dtype: object

In [ ]:
house_df.iloc[0:3]

,House_ID,Location,Bedrooms,Bathrooms,Area_sqft,Year_Built,Parking,Price_Lakhs
0,1,Pune,2.0,1,850.0,2015,1,45
1,2,Mumbai,NaN,2,1200.0,2012,1,120
2,3,Delhi,4.0,3,1800.0,2018,2,95

In [ ]:
house_df.iloc[2,3]

np.int64(3)

In [ ]:
house_df.loc[0:3, ["Location", "Price_Lakhs"]]

    Location  Price_Lakhs
0       Pune           45
1     Mumbai          120
2      Delhi           95
3  Bangalore           85

Select a Single Column

In [ ]:
house_df['Location']

0         Pune
1       Mumbai
2        Delhi
3    Bangalore
4      Chennai
5         Pune
6       Mumbai
7        Delhi
Name: Location, dtype: object

Select Multiple Column

In [ ]:
house_df[['House_ID','Year_Built']]

   House_ID  Year_Built
0         1        2015
1         2        2012
2         3        2018
3         4        2016
4         5        2010
5         6        2019
6         7        2014
7         8        2008

Select Row using Condition

In [ ]:
house_df[house_df['Location']=='Pune']

,House_ID,Location,Bedrooms,Bathrooms,Area_sqft,Year_Built,Parking,Price_Lakhs
0,1,Pune,2.0,1,850.0,2015,1,45
5,6,Pune,3.0,2,1400.0,2019,1,78

Sort Data

In [ ]:
house_df.sort_values(by='Price_Lakhs')

,House_ID,Location,Bedrooms,Bathrooms,Area_sqft,Year_Built,Parking,Price_Lakhs
0,1,Pune,2.0,1,850.0,2015,1,45
7,8,Delhi,2.0,1,800.0,2008,0,55
4,5,Chennai,2.0,1,900.0,2010,0,60
5,6,Pune,3.0,2,1400.0,2019,1,78
3,4,Bangalore,3.0,2,NaN,2016,1,85
2,3,Delhi,4.0,3,1800.0,2018,2,95
1,2,Mumbai,NaN,2,1200.0,2012,1,120
6,7,Mumbai,4.0,3,2000.0,2014,2,150

Describe Attribute Of Data

In [ ]:
house_df.describe()

,House_ID,Bedrooms,Bathrooms,Area_sqft,Year_Built,Parking,Price_Lakhs
count,8.00000,7.000000,8.000000,7.000000,8.000000,8.000000,8.000000
mean,4.50000,2.857143,1.875000,1278.571429,2014.000000,1.000000,86.000000
std,2.44949,0.899735,0.834523,477.717789,3.817254,0.755929,35.286582
min,1.00000,2.000000,1.000000,800.000000,2008.000000,0.000000,45.000000
25%,2.75000,2.000000,1.000000,875.000000,2011.500000,0.750000,58.750000
50%,4.50000,3.000000,2.000000,1200.000000,2014.500000,1.000000,81.500000
75%,6.25000,3.500000,2.250000,1600.000000,2016.500000,1.250000,101.250000
max,8.00000,4.000000,3.000000,2000.000000,2019.000000,2.000000,150.000000

Datatype of each column

In [ ]:
house_df['Price_Lakhs'].dtype

dtype('int64')

In [ ]:
house_df['Location'].dtype

dtype('O')

In [ ]:
house_df.dtypes

House_ID         int64
Location        object
Bedrooms       float64
Bathrooms        int64
Area_sqft      float64
Year_Built       int64
Parking          int64
Price_Lakhs      int64
dtype: object

In [ ]:
house_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   House_ID     8 non-null      int64
 1   Location     8 non-null      object
 2   Bedrooms     7 non-null      float64
 3   Bathrooms    8 non-null      int64
 4   Area_sqft    7 non-null      float64
 5   Year_Built   8 non-null      int64
 6   Parking      8 non-null      int64
 7   Price_Lakhs  8 non-null      int64
dtypes: float64(2), int64(5), object(1)
memory usage: 644.0+ bytes

Counting Unique Values

In [ ]:
house_df.nunique()

House_ID       8
Location       5
Bedrooms       3
Bathrooms      3
Area_sqft      7
Year_Built     8
Parking        3
Price_Lakhs    8
dtype: int64

In [ ]:
house_df["Location"].unique()

array(['Pune', 'Mumbai', 'Delhi', 'Bangalore', 'Chennai'], dtype=object)

In [ ]:
house_df["Location"].value_counts()

Location
Pune         2
Mumbai       2
Delhi        2
Bangalore    1
Chennai      1
Name: count, dtype: int64

Convert Variable Datatype

In [ ]:
house_df['Bathrooms'] = house_df['Bathrooms'].astype(float)

Convert object to category

In [ ]:
house_df["Location"] = house_df["Location"].astype("category")

In [ ]:
house_df.dtypes

House_ID          int64
Location       category
Bedrooms        float64
Bathrooms       float64
Area_sqft       float64
Year_Built        int64
Parking           int64
Price_Lakhs       int64
dtype: object

Student DataFrame

In [ ]:
import pandas as pd
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Sneha", "Rahul", "Pooja", "Kiran"],
    "Age": [19, 20, 21, 20, 22],
    "Gender": ["Male", "Female", "Male", "Female", "Male"],
    "Department": ["CSE", "IT", "ECE", "CSE", "ME"],
    "Marks": [85, 92, 78, 88, 74],
    "Attendance (%)": [90, 95, 85, 92, 80],
    "Internship": ["Yes", "Yes", "No", "Yes", "No"]
}
df = pd.DataFrame(data)
df

   Student_ID   Name  Age  Gender Department  Marks  Attendance (%) Internship
0         101   Amit   19    Male        CSE     85              90        Yes
1         102  Sneha   20  Female         IT     92              95        Yes
2         103  Rahul   21    Male        ECE     78              85         No
3         104  Pooja   20  Female        CSE     88              92        Yes
4         105  Kiran   22    Male         ME     74              80         No

Find Shape of Data

In [ ]:
df.shape

(5, 8)

Find Missing Values

In [ ]:
df.isnull().sum()

Student_ID        0
Name              0
Age               0
Gender            0
Department        0
Marks             0
Attendance (%)    0
Internship        0
dtype: int64

Find Datatype of each column

In [ ]:
df.dtypes

Student_ID         int64
Name              object
Age                int64
Gender            object
Department        object
Marks              int64
Attendance (%)     int64
Internship        object
dtype: object

Indexing , Selecting , Sorting Data

In [ ]:
df.head()

   Student_ID   Name  Age  Gender Department  Marks  Attendance (%) Internship
0         101   Amit   19    Male        CSE     85              90        Yes
1         102  Sneha   20  Female         IT     92              95        Yes
2         103  Rahul   21    Male        ECE     78              85         No
3         104  Pooja   20  Female        CSE     88              92        Yes
4         105  Kiran   22    Male         ME     74              80         No

In [ ]:
df.tail()

   Student_ID   Name  Age  Gender Department  Marks  Attendance (%) Internship
0         101   Amit   19    Male        CSE     85              90        Yes
1         102  Sneha   20  Female         IT     92              95        Yes
2         103  Rahul   21    Male        ECE     78              85         No
3         104  Pooja   20  Female        CSE     88              92        Yes
4         105  Kiran   22    Male         ME     74              80         No

Select Rows using Index

In [ ]:
df.iloc[0]

Student_ID         101
Name              Amit
Age                 19
Gender            Male
Department         CSE
Marks               85
Attendance (%)      90
Internship         Yes
Name: 0, dtype: object

In [ ]:
df.iloc[0:3]

   Student_ID   Name  Age  Gender Department  Marks  Attendance (%) Internship
0         101   Amit   19    Male        CSE     85              90        Yes
1         102  Sneha   20  Female         IT     92              95        Yes
2         103  Rahul   21    Male        ECE     78              85         No

In [ ]:
df.iloc[1,3]

'Female'

Select single row

In [ ]:
df['Student_ID']

0    101
1    102
2    103
3    104
4    105
Name: Student_ID, dtype: int64

Select multiple rows

In [ ]:
df[['Age','Attendance (%)']]

   Age  Attendance (%)
0   19              90
1   20              95
2   21              85
3   20              92
4   22              80

Select rows based on condition

In [ ]:
df[df['Age']==19]

   Student_ID  Name  Age Gender Department  Marks  Attendance (%) Internship
0         101  Amit   19   Male        CSE     85              90        Yes

Sort Data

In [ ]:
df.sort_values(by='Age')

   Student_ID   Name  Age  Gender Department  Marks  Attendance (%) Internship
0         101   Amit   19    Male        CSE     85              90        Yes
1         102  Sneha   20  Female         IT     92              95        Yes
3         104  Pooja   20  Female        CSE     88              92        Yes
2         103  Rahul   21    Male        ECE     78              85         No
4         105  Kiran   22    Male         ME     74              80         No

Describe Attributes of Data

In [ ]:
df.describe()

       Student_ID        Age      Marks  Attendance (%)
count    5.000000   5.000000   5.000000         5.00000
mean   103.000000  20.400000  83.400000        88.40000
std      1.581139   1.140175   7.334848         5.94138
min    101.000000  19.000000  74.000000        80.00000
25%    102.000000  20.000000  78.000000        85.00000
50%    103.000000  20.000000  85.000000        90.00000
75%    104.000000  21.000000  88.000000        92.00000
max    105.000000  22.000000  92.000000        95.00000

Counting Unique Values

In [ ]:
df.nunique()

Student_ID        5
Name              5
Age               4
Gender            2
Department        4
Marks             5
Attendance (%)    5
Internship        2
dtype: int64